name: irc

on: [push]

env:
  COMMIT_MESSAGE: ${{ github.event.commits[0].message }}

jobs:
  notification:
    runs-on: ubuntu-latest
    name: IRC notification
    steps:
      - name: Format message
        id: message
        run: |
          message="${{ github.actor }} pushed $(echo '$COMMIT_MESSAGE' | head -n 1) ${{ github.event.commits[0].url }}"
          echo ::set-output name=message::"${message}"
      - name: IRC notification
        uses: Gottox/irc-message-action@v2
        with:
          channel: '#jack'
          nickname: jackaudio-bot
          message: ${{ steps.message.outputs.message }}
